---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    #pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
    - recipe[sample::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
