name 'sample'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures sample'
long_description 'Installs/Configures sample'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/jbencic/chef-cookbook-sample/issues'
source_url 'https://github.com/jbencic/chef-cookbook-sample'
